### PR TITLE
Fix for offline charging mode

### PR DESCRIPTION
**Pull request by AlexLartsev19**
From https://github.com/divis1969/android_device_meizu_meilan2/commit/5e1ac99b944e6899484757649892d05a71268ef0

### CODE REVIEW

**Comment by Moyster** [comment]
did you try ? Good findings anyway, thanks ;)

**Comment by AlexLartsev19** [comment]
Nope, i can't now :( . What about mothertboard? :-)

**Comment by Moyster** [comment]
https://github.com/Moyster/android_device_meizu_m2note/commit/b8c602ea5c9c06ffdce1fd9a86ac247d4fcb7d25
I also pushed this, we'll see if I can build tonight :)

I bought the same exact model, seems to boot but I have a few things to change / bios settings / bios update to do, that means I need to plug a screen to it :<

**Comment by AlexLartsev19** [comment]
ok, it's very-very good :+1:

**Pull request merged**
